### ISSUE TITLE
 当旭日图中有负值的时候显示的问题

### ISSUE THREAD

**Issue by weixingcai** [Rello/analytics#27] opened 2020-03-04 08:01 UTC
https://jshare.com.cn/temp/ZOGGQw 当旭日图中有负值的时候显示的问题

**Comment by aszlig** [comment] 2020-03-09 22:30
translation: Problems showing when there are negative values in the sunburst chart

**Comment by aszlig** [comment] 2020-03-09 22:30
Maybe duplicate of #26?

**Comment by Rello** [comment] 2020-03-10 11:49
Hello,
this charttype is not supported by DA at the moment.
Additionally, the next release will switch from highcharts to chart.js for licensing reasons.

thank you

**Closed by Rello** 2020-03-10 11:49 UTC
