### ISSUE TITLE
Mounth with 2 digit date error in REST API

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#194] opened 2021-10-08 07:10 UTC
I use REST API to push data to a data set, but it seems that the date collection does not work correctly for mounths with 2 digit.

I push the following via the command : 
`curl --silent -u temperatures:Rv6MsftVDYz8IWoL62Yhz3nZBokXV -d '{"data":[{"Capteur": "28-01205f2dbc64", "Date": "2021-10-08 09:05:41.724115", "Value": "19.125"}]}' -X POST -H 'Content-Type: application/json' https://xxxx/index.php/apps/analytics/api/2.0/adddata/51 > /dev/null`

The result is : 

```

Capteur | Date | Value
-- | -- | --
28-01205f2dbc64 | 2021-010-08 09:05:03 | 19,13
28-01205f2dbc64 | 2021-010-08 09:05:41 | 19,13
```

Mounth is printed : 010 instead of 10. (October).

and Graphic shows January instead of October : 

![Capture d’écran 2021-10-08 à 09 09 23](https://user-images.githubusercontent.com/17098018/136513470-1e5df5c0-e415-4794-ac36-f7a331f9c09a.png)

Chat option is : 
{"scales": {"xAxes": {"time": {"unit" : "day"}}}}

## Server configuration detail

**Operating system:** Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.3.29

**PHP version:** 7.3.29-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 21.0.5 - 21.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - analytics: 3.6.1
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.4
 - carnet: 0.24.2
 - checksum: 1.1.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.3
 - contactsinteraction: 1.2.0
 - cookbook: 0.9.4
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.5
 - documentserver_community: 0.1.11
 - drawio: 1.0.1
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_external: 1.12.0
 - files_markdown: 2.3.4
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_texteditor: 2.14.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - geoblocker: 0.5.1
 - keeweb: 0.6.6
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.9
 - music: 1.3.3
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.1
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.1.2
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.3.2
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.14.2
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather: 1.7.5
 - weather_status: 1.1.0
 - workflowengine: 2.3.1
Disabled:
 - federation


```
</details>

**Comment by Rello** [comment] 2021-10-09 20:00
duplicate of #191

**Closed by Rello** 2021-10-09 20:00 UTC
Labels: bug
