### ISSUE TITLE
Dataload results in error

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#237] opened 2021-12-09 16:58 UTC
I think this issue came up with version 4, but I'm not sure.

Datasource:
https://opendata.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0.csv
columns:
8,9,44

Dataload results in error:

```
sudo -u www-data php /var/www/nextcloud/occ analytics:load 21
An unhandled exception has been thrown:
Error: Cannot use object of type OCP\AppFramework\Http\NotFoundResponse as array in /var/www/nextcloud/apps/analytics/lib/Service/DataloadService.php:139
Stack trace:
#0 /var/www/nextcloud/apps/analytics/lib/Command/Load.php(48): OCA\Analytics\Service\DataloadService->execute()
#1 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Analytics\Command\Load->execute()
#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#7 /var/www/nextcloud/occ(11): require_once('...')
#8 {main}
```

**Comment by doenietzomoeilijk** [comment] 2021-12-13 08:04
I see the same error while fetching a remote JSON dataset.

**Comment by hufnala** [comment] 2021-12-29 12:55
Hi, same here with a own created file. Nextcloud is hosted externally, and failure message mentions "please check logfile". Where can find this file without access to the installation?

ReCreate Issue: 
- New Analytics from scratch
- Import from File
- Select File
[csv File and Screenhshot](https://hufnala.wolkesicher.de/s/SxzrMCRjExByxbx)

**Comment by Rello** [comment] 2022-01-11 18:45
Hello @sirdrakeistda 
sorry for the delay. I am picking up again after a little break.

I tried both ways: 
- realtime on the external data
![Bildschirmfoto 2022-01-11 um 19 43 31](https://user-images.githubusercontent.com/13385119/149002529-969e50a8-eef4-4ff3-baeb-38cacad5cb26.png)

- Internal storage via dataload from UI and also occ
![Bildschirmfoto 2022-01-11 um 19 44 29](https://user-images.githubusercontent.com/13385119/149002655-ea4fa5b2-79a2-4488-b136-473afb294d87.png)
![Bildschirmfoto 2022-01-11 um 19 44 11](https://user-images.githubusercontent.com/13385119/149002611-68ec54e7-8833-45b8-8077-03f311d1ac42.png)

everything is working and I could not reproduce the error.
can you check again? the only thing I could think of is that the external file might have been unavailable temporarily?

please let me know...

**Comment by sirdrakeistda** [comment] 2022-01-11 20:29
Seems to work now. I'm not sure what caused this issue. I will close it. @doenietzomoeilijk If your error persist and is not caused by the json source I could open it again if you want.

@hufnala If you are administrator you could find the logs also in the Settings in the "Logging" section. Be aware of the filter option to get errors, warnings or debug logs.

**Comment by hufnala** [comment] 2022-01-11 20:36
Thanks, will check the next days...

**Comment by doenietzomoeilijk** [comment] 2022-01-12 21:48
I still get the error, but on my end, things might be different because I'm fetching JSON, not CSV. I'll try and store and example workload somewhere and make sure I'm Doing It Right - although the actual error message seems to point at something being actually faulty or not properly error-checked in the code. At least `Cannot use object of type OCP\AppFramework\Http\NotFoundResponse as array in /var/www/html/custom_apps/analytics/lib/Service/DataloadService.php:139` tells me it's trying to feed something into a dataloadservice, but that something suddenly turns out to be a `NotFoundResponse` instead of an array of data (?).

I *am* sure that the remote JSON source I'm attempting to fetch exists and can be reached.

**Comment by sirdrakeistda** [comment] 2022-01-13 00:11
@*doenietzomoeilijk* Maybe it would be helpful if you could share the link of the JSON source.

12.01.2022 22:48:29 Max Roeleveld ***@***.***>:

**Comment by Rello** [comment] 2022-01-13 07:54
@doenietzomoeilijk if you don´t want to share the link public, you can contact me at **analytics at scherello . de**

**Comment by Rello** [comment] 2022-01-14 11:01
I just tried with my test-json and everything works.
I need some more info on your datasource then

URL: https://raw.githubusercontent.com/Rello/analytics/master/sample_data/sample_json.json
Path: json testdata
Timestamp: false

**Closed** 2022-01-27 20:27 UTC
Labels: bug, needs info
