### ISSUE TITLE
High CPU load during dataloads

### ISSUE THREAD

**Issue by dgedgedge** [Rello/analytics#118] opened 2021-03-07 16:57 UTC
Hi,
I am testing on nextcoud 20, Analytics 3.3.3 on up to date Buster on a J4105 cpu.
I am working on the following dataset.
https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
I did build 7 graphics on those data, and similar.
I did select the day upload of the data to my database.
Initialy I did planned to update the graphics each hours => plenty of cron launched at the same time.

The consequence is that on my server the cron.php has last for more than 17h00. (Not yet finished).

My point is that the users may use the function extensively like I did, and the admin of the machine has no mean to understand that the cron is overladed by functions of analytics....

Moreover, the hours for daily loading cannont be changed...

So for future developments I suggest to think of the way to allow the admin to master cpu/machine usage with regards to the analytics users.

Ideas : 
1- In the cron lauch/detach a separated process that will run the database upload (may be 1 by user). This will enables the admin to understand that it's an Analiytics process that is running long.
2- Protect the script by users so that if a load process from user has not finished before the time for the load to restart, a second load is not launched. (E.g. : 1 user is limited to one load process at a time).
3- The time when it was launched also collide with the backup process. At that time the apache is stopped and the database. Idea : enable the admin to set the hour for automatic upload.
4- Nice (change priority) of the user load process in order to limit the impact of the process load on the machine load. 
5- Limit the duration of the load by admin parameters, and warn the user that his (her) process has run for too long.

6- The  occ analytics:load cannot be used by normal users. But may be and occ command could be provided in order for the admin to organize the user request of occ analytics:load, and thus master the time la cpu load for each.
7- Disable the direct conection of the background load and the cron.php. 
8-Add an info to the user showing cpu needed to load the data.

In the hope in improving your development that is very promissing.

Note: If you want to reproduce, Graphics are : 
Loading : External source cvs + Reset data + Load daily

https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
3,4,13
3,4,16
3,4,17
3,4,11
3,4,14

 https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv
 1,3,10
 1,3,11

 https://covid19.who.int/WHO-COVID-19-global-data.csv
 3,1,5
 3,1,7

**Comment by Rello** [comment] 2021-03-07 20:00
Hello,
nice hint on that!
problem is, that your dataset is really huge!
the process needs to loop all rows & columns. thats a lot to do x7
lets see how we can solve this

**Comment by dgedgedge** [comment] 2021-03-07 21:33
> Hello,
> nice hint on that!
> problem is, that your dataset is really huge!
> the process needs to loop all rows & columns. thats a lot to do x7
> lets see how we can solve this

Yes I agree this data set is hudge. But I imagine that some users of my server could have the bad Idea to try to process such data as I did (by hazard).
Before seeing the cron.php issue I was not aware of the size of the data.

As I have multiple users, as an admin I shall insure to "master" the usage of the common ressource to avoid one "bad" user to "break" the server....

I am sure you can find a solution to put some limits, or ways to insure that aspect.

Again Thanks for your contrib to nextcloud. I thing that this module will be usefull to plenty of users in the future.

**Comment by dgedgedge** [comment] 2021-03-07 21:40
> > Hello,
> > nice hint on that!
> > problem is, that your dataset is really huge!
> > the process needs to loop all rows & columns. thats a lot to do x7
> > lets see how we can solve this
> 
> Yes I agree this data set is hudge. But I imagine that some users of my server could have the bad Idea to try to process such data as I did (by hazard).
> Before seeing the cron.php issue I was not aware of the size of the data.
> 
> As I have multiple users, as an admin I shall insure to "master" the usage of the common ressource to avoid one "bad" user to "break" the server....
> 
> I am sure you can find a solution to put some limits, or ways to insure that aspect.
> 
> Again Thanks for your contrib to nextcloud. I thing that this module will be usefull to plenty of users in the future.

I had also an idea that could inprove the data load but not the admin concern : Enable to filter data at the input.

**Comment by dgedgedge** [comment] 2021-03-07 23:04
> Hello,
> nice hint on that!
> problem is, that your dataset is really huge!
> the process needs to loop all rows & columns. thats a lot to do x7
> lets see how we can solve this

I was surprised by your assertion. 
So I did the following php program that takes part of your code: 

```
<?php
$selectedColumns = array();
$selectedColumns[0]=3;
$selectedColumns[1]=4;
$selectedColumns[2]=13;

$file = fopen("file:///tmp/owid-covid-data.csv", "r");
while (($line = fgets($file)) !== false) {
        $rowMinimized = array();
        $row = fgetcsv ( $file , 0 , "," , '"' , "\\" );
        foreach ($selectedColumns as $selectedColumn) {
                    array_push($rowMinimized, $row[$selectedColumn - 1]);
        }
        for ($i=0; $i<3; $i++) {
                print($rowMinimized[$i].",");
        }
        print("\n");
}
?>

```
Trying to extract the code with the issue, and run it.

It takes 
real	0m2,461s
user	0m1,646s
sys	0m0,815s

It seems to me that the issue has to be found somewhere else...
Regrads

**Comment by Rello** [comment] 2021-03-08 07:48
Hi,
I found the issue.
the problem is the database updater. all records are looped; checked if key is available and then do either an update or insert.

I have some ideas already. especially the update-check can be omitted, if the "delete data" is used. this would 1/2 the requests already.
then I will check with the NC team if a mass commit is possible

thank you...

**Comment by Rello** [comment] 2021-03-08 19:34
Just an update.
The database procedure was changed to work with bulk change/commits.
500 updates are collected and committed one time. this will reduce the insert and index rollup by factor 500.

The update of your 73k rows was performed in 2 minutes on my 2GHz Testserver (even so there were a lot of error=null record in the value column)
```
error: 48266
insert: 25118
update: 0
```

**Comment by dgedgedge** [comment] 2021-03-10 07:14
> Just an update.
> The database procedure was changed to work with bulk change/commits.
> 500 updates are collected and committed one time. this will reduce the insert and index rollup by factor 500.
> 
> The update of your 73k rows was performed in 4 minutes on my 2GHz Testserver (even so there were a lot of error=null record in the value column)
> 
> ```
> error: 48266
> insert: 25118
> update: 0
> ```

Thanks a lot for this improvement I look forward to see the result in the next release.
In my special case (Small number of users) this will be perfect.
But don't you think that an improvement is needed for admin of big installation as we know that loading full data sets may lead to heavy cpu load (multiply by users) even with the improvement.
Ref. my first suggestions about admin management of users ?
What is your thinking about that ?

Note : I saw in some post that it should be possible to limit the users able to load data in analytics, but I don't know how yet.

**Comment by Rello** [comment] 2021-03-10 07:19
Hello,
I will release this with the next update.

regarding admin: thats a bigger thing. the jobs are tied to the nextcloud cron. it takes care of all scheduling and also skipping, in case they are too long. thats why only daily/hourly is there and no shorter periods.
But the bigger instances you are talking about also have bigger cpu and databases. currently I did not get any issues reported here. neither by users nor bei NC enterprise support

the question would also be on how to do these settings.
allow users totally no data loads? make the admin select which one to choose? ...?
I don´t have an idea here yet. suggestion welcome

lets see.
this fix will be first

**Closed** 2021-03-13 14:11 UTC
Labels: datasource
