### ISSUE TITLE
console error when using timestamps for 1-column raw data

### ISSUE THREAD

**Issue by kevinkuan1969** [Rello/analytics#384] opened 2024-01-17 11:23 UTC
Nextcloud 28.0.1
Analytics 4.12.0
Ubuntu 23.10
PHP 8.2

There are errors in log reader and wonder why it happened. 
Undefined array key -1 at /var/www/nextcloud/apps/analytics/lib/Controller/DatasourceController.php#146

**Comment by kevinkuan1969** [comment] 2024-01-17 11:25
![image](https://github.com/Rello/analytics/assets/80019930/f0f4fb53-1552-415f-988d-de508a61824b)

**Comment by Rello** [comment] 2024-01-17 11:55
Hi,
thank you for the input. I will look at the source here. some special condition ist not being processed correctly.

**Comment by Rello** [comment] 2024-02-26 10:33
Issue will be fixed with the next release. it was caused by the raw data only containing 1 column...

**Closed** 2024-05-24 20:26 UTC
Labels: bug, pending release
